<?xml version="1.0" encoding="utf-8"?><Database Name="Form" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=RAHUL-JHA;Initial Catalog=Form;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FormConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHIRA" Member="CHIRAs">
    <Type Name="CHIRA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WillAttend" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SPNIKALO" Method="SPNIKALO">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="WillAttend" Parameter="willAttend" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="StatementType" Parameter="statementType" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="SPNIKALOResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WillAttend" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BABA" Method="BABA" IsComposable="true">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="BABAResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WillAttend" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DataChange" Method="DataChange">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="WillAttend" Parameter="willAttend" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NewEmail" Parameter="newEmail" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DataRemove" Method="DataRemove">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
</Database>